<template>
    <Row class="item">
        <bread-crumb></bread-crumb>
        <item-detail :itemDetail="itemInfo" :groupDetail="groupDetail"
        :browseList="browseList"></item-detail>
    </Row>
</template>
<script>
import BreadCrumb from '../common/BreadCrumb'
import ItemDetail from './ItemDetail'
export default {
    name:'ItemId',
    data(){
        return {
            itemInfo:{
                name:'良品铺子 手剥松子218g 坚果炒货 巴西松子',
                discount:{
                    label:'折扣价',
                    value:'56.90'
                },
                mktPrice:{
                    label:'原价',
                    value:'98.00',
                },
                priceUnit:{
                    label:'元',
                    value:'¥'
                },
                freprice:'10',
                thumbList:[
                    {
                        label:'',
                        src:'../../../static/i/item/01_small.jpg',
                        value:'1'
                    },
                    {
                        label:'',
                        src:'../../../static/i/item/02_small.jpg',
                        value:'2'
                    },
                    {
                        label:'',
                        src:'../../../static/i/item/03_small.jpg',
                        value:'3'
                    }
                ],
                previewImg:'../../../static/i/item/01_mid.jpg',
                zoomImg:'../../../static/i/item/01.jpg',
                monthStatic:{
                    label:'月销量',
                    value:'1015'
                },
                totalSellCount:{
                    label:'累计销量',
                    value:'6015'
                },
                commentStatic:{
                    label:'累计评价',
                    value:'640'
                },
                params:[
                    {
                        label:'口味',
                        value:'1',
                        catList:[
                            {
                                label:'原味',
                                value:'1'
                            },
                            {
                                label:'奶油',
                                value:'2'
                            },
                            {
                                label:'炭烧',
                                value:'3'
                            },
                            {
                                label:'咸香',
                                value:'4'
                            }
                        ]
                    },
                    {
                        label:'包装',
                        value:'2',
                        catList:[
                            {
                                label:'手袋单人份',
                                value:'1'
                            },
                            {
                                label:'礼盒双人份',
                                value:'2'
                            },
                            {
                                label:'全家福礼包',
                                value:'3'
                            }
                        ]
                    },
                    {
                        label:'数量',
                        value:'3',
                        maxNum:999
                    }
                ],
                activity:{
                    label:'店铺优惠',
                    value:'购物满2件打8折，满3件7折'
                },
                coupon:{
                    label:'优惠券',
                    value:[
                        {
                            label:'125减5',
                            value:'1'
                        },
                        {
                            label:'198减10',
                            value:'2'
                        },
                        {
                            label:'298减20',
                            value:'3'
                        },
                        {
                            label:'398减30',
                            value:'4'
                        }
                    ]
                }
            },
            groupDetail:[
                {
                    imgSrc:'../../../static/i/item/cp.jpg',
                    label:'萨拉米 1+1小鸡腿',
                    discountPrice:29.90,
                    mktPrice:99.90
                },{
                    imgSrc:'../../../static/i/item/cp2.jpg',
                    label:'ZEK 原味海苔',
                    discountPrice:8.90,
                    mktPrice:19.90
                }
            ],
            browseList:[
                {
                    label:'【三只松鼠_开口松子】零食坚果特产炒货东北红松子原味',
                    imgSrc:'../../../static/i/item/browse1.jpg',
                    value:'1',
                    price:'35.90'
                },
                {
                    label:'【三只松鼠_开口松子】零食坚果特产炒货东北红松子原味',
                    imgSrc:'../../../static/i/item/browse1.jpg',
                    value:'2',
                    price:'35.90'
                },
                {
                    label:'【三只松鼠_开口松子】零食坚果特产炒货东北红松子原味',
                    imgSrc:'../../../static/i/item/browse1.jpg',
                    value:'3',
                    price:'35.90'
                }
            ]
        }
    },
    components:{
        BreadCrumb:BreadCrumb,
        ItemDetail:ItemDetail
    }
}
</script>