<template>
    <div class="prd-category">
        <Row :class="'floor-'+index" v-for="(item,index) in prdCategoryList" :key="item.value" 
            :value="item.value">
            <Row class="cat-container">
                <Col span="12" class="shop-title">
                    <h4>{{item.h4Text}}</h4>
                    <h3>{{item.h3Text}}</h3>
                    <Col span="12" class="today-brands">
                        <a v-for="bItem in item.brands" href="bItem.href" 
                            :key="bItem.value" :value="bItem.value">{{bItem.label}}</a>
                    </Col>
                    <span class="more">
                        <a href="">
                            更多美味
                            <i class="arrow-right"></i>
                        </a>
                    </span>
                </Col>
            </Row>
            <Row class="flood-four">
                <div class="text-one">
                    <div class="word">
                        <a class="outer" v-for="kwItem in item.keywords" :key="kwItem.value" :value="kwItem.value">
                            <span class="inner">
                                <b class="text">{{kwItem.label}}</b>
                            </span>
                        </a>
                    </div>
                    <a class="desc" href="">
                        <div class="outer-con">
                            <div class="title">{{item.title}}</div>
                            <div class="sub-title">{{item.subTitle}}</div>
                        </div>
                        <img v-lazy="item.bgSrc"/>
                    </a>
                    <div class="top-right"></div>
                </div>
                <div class="prd-col" v-for="(prd,pIndex) in item.products" :key="prd.value" :value="prd.value">
                    <div v-if="pIndex==2 || pIndex==5" class="prd-big">
                        <div class="outer-con">
                            <div class="title">{{prd.title}}</div>
                            <div class="sub-title">{{prd.subTitle}}</div>
                            <i class="shopping-basket"></i>
                        </div>
                        <a>
                            <img v-lazy="prd.src" />
                        </a>
                    </div>
                    <div v-else-if="pIndex==1 || pIndex==4" class="prd-small sug">
                        <div class="outer-con">
                            <div class="title">{{prd.title}}</div>
                            <div class="sub-title">{{prd.subTitle}}</div>
                            <i class="shopping-basket"></i>
                        </div>
                        <a>
                            <img v-lazy="prd.src" />
                        </a>
                    </div>
                    <div v-else class="prd-small">
                        <div class="outer-con">
                            <div class="title">{{prd.title}}</div>
                            <div class="sub-title">{{prd.subTitle}}</div>
                            <i class="shopping-basket"></i>
                        </div>
                        <a>
                            <img v-lazy="prd.src" />
                        </a>
                    </div>
                </div>
            </Row>
        </Row>
    </div>
</template>
<script>
export default{
    name:'prdCategory',
    data(){
        return {
            prdCategoryList:[
                {
                    value:'1',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },
                {
                    value:'2',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'3',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'4',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'5',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'6',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'7',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'8',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                },{
                    value:'9',
                    h4Text:'甜品',
                    h3Text:'每一道甜品都有一个故事',
                    title:'开抢啦！',
                    subTitle:'零食大礼包',
                    bgSrc:'../../../static/i/home/act1.png',
                    brands:[
                        {
                            label:'桂花糕',
                            value:'1',
                            href:'#1'
                        },
                        {
                            label:'奶皮酥',
                            value:'2',
                            href:'#2'
                        },
                        {
                            label:'栗子糕',
                            value:'3',
                            href:'#3'
                        },
                        {
                            label:'马卡龙',
                            value:'4',
                            href:'#4'
                        },
                        {
                            label:'铜锣烧',
                            value:'5',
                            href:'#5'
                        },
                        {
                            label:'豌豆黄',
                            value:'6',
                            href:'#6'
                        }
                    ],
                    keywords:[
                        {
                            value:'1',
                            label:'核桃'
                        },
                        {
                            value:'2',
                            label:'核桃'
                        },{
                            value:'3',
                            label:'核桃'
                        },{
                            value:'4',
                            label:'核桃'
                        },{
                            value:'5',
                            label:'核桃'
                        },{
                            value:'6',
                            label:'核桃'
                        }
                    ],
                    products:[
                        {
                            value:'1',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/1.jpg'
                        },
                        {
                            value:'2',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/2.jpg'
                        },
                        {
                            value:'3',
                            title:'小优布丁',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        },
                        {
                            value:'4',
                            title:'雪之恋和风大福',
                            subTitle:'6.8',
                            src:'../../../static/i/home/4.jpg'
                        },
                        {
                            value:'5',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/3.jpg'
                        },
                        {
                            value:'6',
                            title:'雪之恋和风大福',
                            subTitle:'13.8',
                            src:'../../../static/i/home/5.jpg'
                        }
                    ]
                }
            ]
        }
    }
}
</script>
<style lang="less" scoped>
@import url('../../assets/c/prdcategory.less');   
</style>